
server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservice
    username: root
    password: Test123@@
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
